### ISSUE TITLE
Certificate signed by unknown authority

### ISSUE THREAD

**Issue by miminar** [projectatomic/atomic-enterprise-training#10]
The first time `oc` command is [run](https://github.com/projectatomic/atomic-enterprise-training/blob/master/eap-latest-setup.md#node-labels) as `root` I get:

    oc get nodes
    Unable to connect to the server: x509: certificate signed by unknown authority

I need to run:

    export KUBECONFIG=/etc/openshift/master/admin.kubeconfig

to get it working.

Is it the way it's supposed to work? Does the above line belong to the tutorial?

**Comment by ashcrow** [comment]
Looks like it should be added:

https://docs.openshift.org/latest/getting_started/administrators.html#downloading-the-binary

**Comment by eparis** [comment]
I'm not sure who is doing it (almost certainly the ansible installer) but you should have a $HOME/.kube/config file which oc uses by default. It should have the ca cert embeded...

**Comment by aveshagarwal** [comment]
ansible installer is creating $HOME/.kube/config file and I have not seen this issue myself.

**Comment by ashcrow** [comment]
@miminar could it be that your local instance has had some manual changes? @eparis and @aveshagarwal are correct in pointing out the ansible installer does copy the file to ```/root/.kube/config``` ([reference](https://github.com/projectatomic/atomic-enterprise-ansible/blame/183b94da24414de6b68ba8e7a643fc582755aae2/roles/openshift_master/tasks/main.yml#L146-L148)) which means that it should work out of the gate. However, if you've done something to regenerate it is possible that what is in your ```/root/.kube/config``` no longer matches ```/etc/openshift/master/admin.kubeconfig```.

**Comment by miminar** [comment]
Yes, that's it. Removing `~/.kube/config` and running ansible installer again solves the issue. Thanks! Closing this.
